# Generated by Django 5.0.6 on 2024-05-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='position',
            field=models.CharField(default='developer', max_length=255),
        ),
    ]
